remote_theme: "mmistakes/minimal-mistakes@4.23.0"
plugins: ["jekyll-include-cache", "jekyll-feed"]

logo: https://www.gravatar.com/avatar/cf9d2998c0d9cb26334028f72185fe38
minimal_mistakes_skin: "mint"
title: "Alexis Dumas"
subtitle: "Homepage"
